name: versamammo_pretrain
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py39h6a678d5_7
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.9.24=h06a4308_0
  - certifi=2024.8.30=py39h06a4308_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - comm=0.2.2=pyhd8ed1ab_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.1.0=0
  - dataclasses=0.8=pyh6d0b6a4_7
  - debugpy=1.6.7=py39h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.13.1=py39h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - fvcore=0.1.5.post20221221=pyhd8ed1ab_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py39h06a4308_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - iopath=0.1.9=pyhd8ed1ab_0
  - ipykernel=6.29.3=pyhd33586a_0
  - ipython=8.18.1=pyh707e725_3
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=py39h06a4308_0
  - joblib=1.4.2=py39h06a4308_0
  - jpeg=9e=h5eee18b_1
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py39hf3d152e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=13.2.0=h807b86a_5
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.3=py39h5eee18b_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.8=py39h5eee18b_0
  - mkl_random=1.2.4=py39hdb19cb5_0
  - mpmath=1.3.0=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py39h06a4308_0
  - numpy=1.26.4=py39h5f9d8c6_0
  - numpy-base=1.26.4=py39hb5e798b_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.15=h5eee18b_0
  - packaging=23.2=py39h06a4308_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.2.0=py39h5eee18b_0
  - pip=23.3.1=py39h06a4308_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - portalocker=2.3.0=py39h06a4308_1
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.8=py39hd1e30aa_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.19=h955ad1f_0
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=2.4.1=py3.9_cuda12.1_cudnn9.1.0_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py39h5eee18b_0
  - pyzmq=25.1.2=py39h6a678d5_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py39h06a4308_1
  - scikit-learn=1.5.1=py39h1128e8f_0
  - scipy=1.12.0=py39h5f9d8c6_0
  - setuptools=68.2.2=py39h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.12=pyh04b8f61_3
  - tabulate=0.9.0=py39h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - termcolor=2.1.0=py39h06a4308_0
  - threadpoolctl=3.5.0=py39h2f386ee_0
  - tk=8.6.12=h1ccaba5_0
  - torchmetrics=0.10.3=pyhd8ed1ab_0
  - torchtriton=3.0.0=py39
  - tornado=6.4=py39hd1e30aa_0
  - tqdm=4.65.0=py39hb070fc8_0
  - traitlets=5.14.2=pyhd8ed1ab_0
  - urllib3=2.1.0=py39h06a4308_1
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.41.2=py39h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.4.6=h5eee18b_0
  - yacs=0.1.6=pyhd3eb1b0_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==2.1.0
      - accelerate==1.5.2
      - aenum==3.1.15
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - bypy==1.8.9
      - contourpy==1.3.0
      - cosine-annealing-warmup==2.0
      - cycler==0.12.1
      - dicomsdl==0.109.4
      - dill==0.4.0
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - fonttools==4.54.1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - ftfy==6.3.1
      - grpcio==1.67.0
      - huggingface-hub==0.26.0
      - hydra-core==1.3.2
      - imageio==2.37.0
      - importlib-resources==6.4.5
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - lightly==1.5.19
      - lightly-utils==0.0.2
      - lightning-utilities==0.14.2
      - lxml==5.3.0
      - markdown==3.7
      - matplotlib==3.9.2
      - multidict==6.2.0
      - multiprocess==0.70.18
      - nvidia-ml-py==12.570.86
      - nvitop==1.4.2
      - open-clip-torch==3.2.0
      - opencv-python==4.10.0.84
      - openpyxl==3.1.5
      - pandas==2.2.3
      - patsy==1.0.1
      - peft==0.15.1
      - propcache==0.3.1
      - protobuf==5.28.2
      - pydantic==2.11.1
      - pydantic-core==2.33.0
      - pydicom==2.4.4
      - pydot==3.0.3
      - pyparsing==3.2.0
      - python-graphviz==0.20.3
      - python-pptx==1.0.2
      - pytorch-lightning==2.5.1
      - pytz==2024.2
      - regex==2024.11.6
      - requests-toolbelt==1.0.0
      - safetensors==0.4.5
      - scikit-image==0.24.0
      - scikit-posthocs==0.11.4
      - seaborn==0.13.2
      - statannotations==0.7.2
      - statsmodels==0.14.4
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tifffile==2024.8.30
      - timm==1.0.22
      - tokenizers==0.21.1
      - torcheval==0.0.7
      - torchvision==0.19.1
      - transformers==4.50.3
      - typing-extensions==4.13.0
      - typing-inspection==0.4.0
      - tzdata==2024.2
      - werkzeug==3.0.4
      - xlrd==2.0.2
      - xlsxwriter==3.2.2
      - yarl==1.18.3
prefix: /home/fuxianghuang/anaconda3/envs/versamammo_pretrain
