name: zjy
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - alsa-lib=1.2.12=h4ab18f5_0
  - aom=3.9.1=hac33072_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - binutils_impl_linux-64=2.38=h2a08ee3_1
  - blas=1.0=openblas
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.2=heb4867d_0
  - ca-certificates=2024.9.24=h06a4308_0
  - cairo=1.18.0=hebfffa5_3
  - comm=0.2.1=py39h06a4308_0
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.6.7=py39h6a678d5_0
  - double-conversion=3.3.0=h59595ed_0
  - exceptiongroup=1.2.0=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h5888daf_0
  - ffmpeg=6.1.2=gpl_hebc05b9_101
  - fftw=3.3.9=h5eee18b_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gcc=12.1.0=h9ea6d83_10
  - gcc_impl_linux-64=12.1.0=hea43390_17
  - gdcm=2.8.9=py39h33cf49a_10
  - gdk-pixbuf=2.42.12=hb9ae30d_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - gmp=6.3.0=hac33072_2
  - gnutls=3.8.7=h32866dd_0
  - graphite2=1.3.13=h59595ed_1003
  - harfbuzz=9.0.0=hda332d3_1
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - icu=75.1=he02047a_0
  - imath=3.1.12=h7955e40_0
  - importlib-metadata=7.0.1=py39h06a4308_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - intel-openmp=2022.0.1=h06a4308_3633
  - ipykernel=6.29.5=py39h06a4308_0
  - ipython=8.15.0=py39h06a4308_0
  - jasper=4.2.4=h536e39c_0
  - jedi=0.18.1=py39h06a4308_1
  - json-c=0.17=h1220068_1
  - jupyter_client=8.6.0=py39h06a4308_0
  - jupyter_core=5.7.2=py39h06a4308_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.2=cxx17_he02047a_1
  - libaec=1.1.3=h59595ed_0
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libass=0.17.3=h1dc1e6a_0
  - libblas=3.9.0=25_linux64_openblas
  - libcblas=3.9.0=25_linux64_openblas
  - libclang-cpp18.1=18.1.8=default_hf981a13_5
  - libclang-cpp19.1=19.1.2=default_hb5137d0_1
  - libclang13=19.1.2=default_h9c6a7e4_1
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.10.1=hbbe4b11_0
  - libdeflate=1.22=hb9d3cd8_0
  - libdrm=2.4.123=hb9d3cd8_0
  - libedit=3.1.20191231=he28a2e2_2
  - libegl=1.7.0=ha4b6fd6_1
  - libev=4.33=hd590300_2
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-devel_linux-64=12.1.0=h1ec3361_17
  - libgcc-ng=14.2.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgl=1.7.0=ha4b6fd6_1
  - libglib=2.82.2=h2ff4ddf_0
  - libglu=9.0.0=ha6d2627_1004
  - libglvnd=1.7.0=ha4b6fd6_1
  - libglx=1.7.0=ha4b6fd6_1
  - libgomp=14.2.0=h77fa898_1
  - libhwloc=2.11.1=default_hecaa2ac_1000
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=25_linux64_openblas
  - liblapacke=3.9.0=25_linux64_openblas
  - libllvm18=18.1.8=h8b73ec9_2
  - libllvm19=19.1.2=ha7bfdaf_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.4=h7f98852_1002
  - libopenblas=0.3.28=pthreads_h94d23a6_0
  - libopencv=4.10.0=qt6_py39h0b609d9_603
  - libopenvino=2024.3.0=h2da1b83_0
  - libopenvino-auto-batch-plugin=2024.3.0=hb045406_0
  - libopenvino-auto-plugin=2024.3.0=hb045406_0
  - libopenvino-hetero-plugin=2024.3.0=h5c03a75_0
  - libopenvino-intel-cpu-plugin=2024.3.0=h2da1b83_0
  - libopenvino-intel-gpu-plugin=2024.3.0=h2da1b83_0
  - libopenvino-intel-npu-plugin=2024.3.0=h2da1b83_0
  - libopenvino-ir-frontend=2024.3.0=h5c03a75_0
  - libopenvino-onnx-frontend=2024.3.0=h07e8aee_0
  - libopenvino-paddle-frontend=2024.3.0=h07e8aee_0
  - libopenvino-pytorch-frontend=2024.3.0=he02047a_0
  - libopenvino-tensorflow-frontend=2024.3.0=h39126c6_0
  - libopenvino-tensorflow-lite-frontend=2024.3.0=he02047a_0
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.44=hadc24fc_0
  - libpq=16.4=h2d7952a_3
  - libprotobuf=4.25.3=hd5b35b9_1
  - librsvg=2.58.4=hc0ffecb_0
  - libsanitizer=12.1.0=ha89aaad_17
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.47.0=hadc24fc_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=12.3.0=hc0a3c3a_7
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.7.0=he137b08_1
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.22.0=hb711507_0
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.7.0=h2c5496b_1
  - libxml2=2.12.7=he7c6b58_4
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=19.1.2=h024ca30_0
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mkl=2023.2.0=h84fe81f_50496
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.10=py39h191f12f_1
  - mkl_random=1.2.7=py39h1128e8f_0
  - mysql-common=9.0.1=h266115a_2
  - mysql-libs=9.0.1=he0572af_2
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py39h06a4308_0
  - nettle=3.9.1=h7ab15ed_0
  - ocl-icd=2.3.2=hd590300_1
  - opencv=4.10.0=qt6_py39h6da081f_603
  - openexr=3.2.2=h04e0de5_2
  - openh264=2.4.1=h59595ed_0
  - openjpeg=2.5.2=h488ebb8_0
  - openldap=2.6.8=hedd0468_0
  - openssl=3.3.2=hb9d3cd8_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=24.1=py39h06a4308_0
  - pango=1.54.0=h4c5309f_1
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.44=hba22ea6_2
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=24.0=py39h06a4308_0
  - pixman=0.43.2=h59595ed_0
  - platformdirs=3.10.0=py39h06a4308_0
  - prompt-toolkit=3.0.43=py39h06a4308_0
  - psutil=5.9.0=py39h5eee18b_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pugixml=1.14=h59595ed_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-opencv=4.10.0=qt6_py39h1b361a7_603
  - pygments=2.15.1=py39h06a4308_1
  - python=3.9.18=h0755675_1_cpython
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python_abi=3.9=5_cp39
  - pyzmq=25.1.2=py39h6a678d5_0
  - qt6-main=6.7.2=hb12f9c5_5
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=ha2e4443_0
  - sqlite=3.32.3=hcee41ef_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - svt-av1=2.1.2=hac33072_0
  - sysroot_linux-64=2.17=h4a8ded7_18
  - tbb=2021.13.0=h84d6215_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.1=py39h5eee18b_0
  - traitlets=5.14.3=py39h06a4308_0
  - typing_extensions=4.11.0=py39h06a4308_0
  - wayland=1.23.0=h5291e77_0
  - wayland-protocols=1.37=hd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.43.0=py39h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.43=hb9d3cd8_0
  - xorg-libice=1.1.1=hb9d3cd8_1
  - xorg-libsm=1.2.4=he73a12e_1
  - xorg-libx11=1.8.10=h4f16b4b_0
  - xorg-libxau=1.0.11=hb9d3cd8_1
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.2=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.11=hb9d3cd8_1
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.5=hb9d3cd8_4
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - accelerate==0.34.2
      - ace-tools==0.0
      - addict==2.4.0
      - aenum==3.1.15
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - albucore==0.0.24
      - albumentations==2.0.8
      - altair==5.4.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.6.0
      - async-timeout==4.0.3
      - attrs==24.2.0
      - av==13.1.0
      - binary-cuda==0.1
      - bitsandbytes==0.44.1
      - bleach==6.1.0
      - blinker==1.8.2
      - blis==1.0.1
      - braceexpand==0.1.7
      - cachetools==5.5.0
      - catalogue==2.0.10
      - certifi==2024.7.4
      - cffi==1.17.1
      - cfgv==3.4.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpathlib==0.20.0
      - cloudpickle==3.1.1
      - cmake==3.30.4
      - confection==0.1.5
      - configargparse==1.7
      - contexttimer==0.3.3
      - contourpy==1.2.1
      - conv2d==0.0.0
      - conv2d-cuda==0.0.0
      - cosine-annealing-warmup==2.0
      - cubinlinker-cu11==0.3.0.post2
      - cuda-python==11.8.5.post1
      - cudf-cu11==24.8.3
      - cuml-cu11==24.8.0
      - cupy-cuda11x==13.3.0
      - cycler==0.12.1
      - cymem==2.0.8
      - dash==2.18.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dask==2024.7.1
      - dask-cuda==24.8.2
      - dask-cudf-cu11==24.8.3
      - dask-expr==1.1.9
      - dataclasses-json==0.6.7
      - datasets==3.1.0
      - decorator==4.4.2
      - decord==0.6.0
      - deepspeed==0.15.4
      - diffusers==0.16.0
      - dill==0.3.8
      - distlib==0.3.9
      - distributed==2024.7.1
      - distributed-ucxx-cu11==0.39.1
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - easydict==1.9
      - efficientnet-pytorch==0.7.1
      - einops==0.8.0
      - einops-exts==0.0.4
      - et-xmlfile==2.0.0
      - eval-type-backport==0.2.0
      - ewconv2d==0.0.0
      - fairscale==0.4.4
      - fastapi==0.115.0
      - fastjsonschema==2.20.0
      - fastrlock==0.8.3
      - ffmpy==0.4.0
      - filelock==3.15.4
      - fire==0.7.0
      - flash-attn==2.6.3
      - flask==3.0.3
      - fonttools==4.53.0
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - ftfy==6.3.0
      - fuzzywuzzy==0.18.0
      - fvcore==0.1.5.post20221221
      - gemmconv==0.0.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - grad-cam==1.5.4
      - gradio==4.44.1
      - gradio-client==1.3.0
      - h11==0.14.0
      - h5py==3.12.1
      - hf-xet==1.1.5
      - hjson==3.1.0
      - httpcore==1.0.5
      - httpx==0.27.2
      - huggingface-hub==0.33.1
      - hydra-core==1.3.2
      - identify==2.6.1
      - idna==3.7
      - im-col==0.0.0
      - imageio==2.34.2
      - imageio-ffmpeg==0.5.1
      - importlib-resources==6.4.0
      - iopath==0.1.10
      - ipywidgets==8.1.5
      - itsdangerous==2.2.0
      - jieba==0.42.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonargparse==4.32.1
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyterlab-widgets==3.0.13
      - kaggle==1.6.17
      - kiwisolver==1.4.5
      - langcodes==3.4.1
      - language-data==1.2.0
      - lazy-loader==0.4
      - libucx-cu11==1.15.0.post2
      - lightly==1.5.19
      - lightly-utils==0.0.2
      - lightning==2.4.0
      - lightning-utilities==0.11.8
      - lit==18.1.8
      - llamafactory==0.9.1.dev0
      - llm-blender==0.0.2
      - llvmlite==0.43.0
      - locket==1.0.0
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.26.1
      - mask-conv2d==0.1
      - maskconv2d==0.1
      - matplotlib==3.9.0
      - mdurl==0.1.2
      - memory-profiler==0.61.0
      - monai==1.5.0
      - moviepy==1.0.3
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - murmurhash==1.0.10
      - mypy-extensions==1.0.0
      - narwhals==1.9.4
      - nbformat==5.10.4
      - networkx==3.2.1
      - new-conv==0.0.0
      - ninja==1.11.1.1
      - nltk==3.9.1
      - nodeenv==1.9.1
      - numba==0.60.0
      - numpy==2.0.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - nvtx==0.2.10
      - omegaconf==2.3.0
      - open-clip-torch==2.27.0
      - open3d==0.18.0
      - opencv-python==4.10.0.84
      - opencv-python-headless==4.5.5.64
      - opendatasets==0.1.22
      - openpyxl==3.1.5
      - orjson==3.10.7
      - pandas==2.2.2
      - partd==1.4.2
      - peft==0.12.0
      - pillow==10.4.0
      - plotly==5.24.1
      - portalocker==2.10.1
      - pre-commit==4.0.1
      - preshed==3.0.9
      - proglog==0.1.10
      - progressbar2==4.5.0
      - propcache==0.2.0
      - protobuf==3.20.0
      - ptxcompiler-cu11==0.8.1.post2
      - py-cpuinfo==9.0.0
      - pyarrow==16.1.0
      - pycocoevalcap==1.2
      - pycocotools==2.0.8
      - pycparser==2.22
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydeck==0.9.1
      - pydicom==2.4.4
      - pydub==0.25.1
      - pylibjpeg==2.0.1
      - pylibjpeg-libjpeg==2.2.0
      - pylibraft-cu11==24.8.1
      - pynvml==11.4.1
      - pyparsing==3.1.2
      - pyquaternion==0.9.9
      - pyre-extensions==0.0.23
      - python-magic==0.4.27
      - python-multipart==0.0.12
      - python-slugify==8.0.4
      - python-utils==3.9.0
      - pytorch-lightning==2.4.0
      - pytorch-triton==3.1.0+cf34004b8a
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyyaml-env-tag==0.1
      - raft-dask-cu11==24.8.1
      - rapids-dask-dependency==24.8.0
      - referencing==0.35.1
      - regex==2024.9.11
      - requests==2.32.3
      - retrying==1.3.4
      - rich==13.8.1
      - rmm-cu11==24.8.2
      - rouge-chinese==1.0.3
      - rpds-py==0.20.0
      - ruff==0.6.8
      - safetensors==0.4.3
      - salesforce-lavis==1.0.1
      - scikit-image==0.24.0
      - scikit-learn==1.5.1
      - scipy==1.13.1
      - semantic-version==2.10.0
      - sentencepiece==0.1.98
      - sentry-sdk==2.14.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - shtab==1.7.1
      - simsimd==6.5.3
      - smart-open==7.0.5
      - smmap==5.0.1
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soundfile==0.12.1
      - spacy==3.8.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - sse-starlette==2.1.3
      - starlette==0.38.6
      - streamlit==1.39.0
      - stringzilla==3.12.6
      - submitit==1.5.2
      - sympy==1.13.1
      - tabulate==0.9.0
      - tblib==3.0.0
      - tenacity==9.0.0
      - termcolor==2.5.0
      - text-unidecode==1.3
      - thinc==8.3.2
      - threadpoolctl==3.5.0
      - tifffile==2024.7.2
      - tiktoken==0.8.0
      - timm==1.0.13
      - tokenizers==0.21.2
      - toml==0.10.2
      - tomlkit==0.12.0
      - toolz==1.0.0
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torcheval==0.0.7
      - torchmetrics==0.10.3
      - torchvision==0.20.1+cu121
      - tqdm==4.66.4
      - transformers==4.52.0
      - treelite==4.3.0
      - triton==3.1.0
      - trl==0.16.1
      - ttach==0.0.3
      - typer==0.12.5
      - typeshed-client==2.7.0
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tyro==0.8.14
      - tzdata==2024.1
      - ucx-py-cu11==0.39.2
      - ucxx-cu11==0.39.1
      - urllib3==2.2.2
      - uvicorn==0.31.0
      - virtualenv==20.27.0
      - visual-genome==1.1.1
      - wandb==0.18.2
      - wasabi==1.1.3
      - watchdog==5.0.3
      - weasel==0.4.1
      - webdataset==0.2.100
      - webencodings==0.5.1
      - websockets==12.0
      - werkzeug==3.0.4
      - widgetsnbextension==4.0.13
      - wrapt==1.16.0
      - xxhash==3.5.0
      - yacs==0.1.8
      - yarl==1.17.1
      - zict==3.0.0
      - zipp==3.19.2
prefix: /home/jiayi/anaconda3/envs/zjy
